import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import Ajv2020 from 'ajv/dist/2020.js';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const manifestDirectory = join(packageRoot, 'manifests/v1');
const schemaPath = join(packageRoot, 'schema/integration-manifest.schema.json');
const generatedJsonPath = join(packageRoot, 'generated/v1/integrations.json');
const generatedTypeScriptPath = join(packageRoot, 'src/generated/v1.ts');
const checkOnly = process.argv.includes('--check');

const schema = JSON.parse(await readFile(schemaPath, 'utf8'));
const ajv = new Ajv2020({ allErrors: true, strict: true });
const validate = ajv.compile(schema);
const compareText = (left, right) => (left < right ? -1 : left > right ? 1 : 0);

const manifestFileNames = (await readdir(manifestDirectory))
  .filter((fileName) => fileName.endsWith('.json'))
  .sort();
const serviceIds = new Set();
const toolNames = new Set();
const integrations = [];

for (const fileName of manifestFileNames) {
  const manifest = JSON.parse(await readFile(join(manifestDirectory, fileName), 'utf8'));
  if (!validate(manifest)) {
    throw new Error(
      `Invalid integration manifest ${fileName}: ${ajv.errorsText(validate.errors, { separator: '; ' })}`
    );
  }
  if (`${manifest.serviceId}.json` !== fileName) {
    throw new Error(`Manifest ${fileName} must match service ID ${manifest.serviceId}`);
  }
  if (serviceIds.has(manifest.serviceId)) {
    throw new Error(`Duplicate service ID: ${manifest.serviceId}`);
  }
  serviceIds.add(manifest.serviceId);

  const tools = [...manifest.tools].sort((left, right) => compareText(left.name, right.name));
  for (const tool of tools) {
    if (toolNames.has(tool.name)) {
      throw new Error(`Duplicate public tool ID: ${tool.name}`);
    }
    toolNames.add(tool.name);
  }

  integrations.push({
    schemaVersion: manifest.schemaVersion,
    serviceId: manifest.serviceId,
    tools,
  });
}

integrations.sort((left, right) => compareText(left.serviceId, right.serviceId));
const generated = { schemaVersion: '1.0', integrations };
const jsonOutput = `${JSON.stringify(generated, null, 2)}\n`;
const serviceIdUnion = integrations.map(({ serviceId }) => `'${serviceId}'`).join(' | ');
const typeScriptOutput = `/* This file is generated by scripts/generate.mjs. Do not edit directly. */
export type BuiltInServiceId = ${serviceIdUnion};

export interface PublicToolContract {
  readonly name: string;
  readonly description: string;
  readonly inputSchema: Readonly<Record<string, unknown>>;
}

export interface IntegrationContractV1 {
  readonly schemaVersion: '1.0';
  readonly integrations: readonly {
    readonly schemaVersion: '1.0';
    readonly serviceId: BuiltInServiceId;
    readonly tools: readonly PublicToolContract[];
  }[];
}

export const integrationContractV1: IntegrationContractV1 = ${JSON.stringify(generated, null, 2)};

export interface PublicToolDefinition {
  readonly serviceId: BuiltInServiceId;
  readonly name: string;
  readonly description: string;
  readonly inputSchema: Readonly<Record<string, unknown>>;
}

export const publicToolDefinitionsByService = Object.freeze(
  Object.fromEntries(
    integrationContractV1.integrations.map((integration) => [
      integration.serviceId,
      Object.freeze(
        integration.tools.map((tool) =>
          Object.freeze({ ...tool, serviceId: integration.serviceId })
        )
      ),
    ])
  )
) as unknown as Readonly<Record<BuiltInServiceId, readonly PublicToolDefinition[]>>;
`;

async function assertCurrent(path, expected) {
  let actual;
  try {
    actual = await readFile(path, 'utf8');
  } catch {
    throw new Error(`Generated artifact is missing: ${path}`);
  }
  if (actual !== expected) {
    throw new Error(`Generated artifact is stale: ${path}. Run pnpm contracts:generate.`);
  }
}

if (checkOnly) {
  await assertCurrent(generatedJsonPath, jsonOutput);
  await assertCurrent(generatedTypeScriptPath, typeScriptOutput);
} else {
  await mkdir(dirname(generatedJsonPath), { recursive: true });
  await mkdir(dirname(generatedTypeScriptPath), { recursive: true });
  await writeFile(generatedJsonPath, jsonOutput);
  await writeFile(generatedTypeScriptPath, typeScriptOutput);
}
